config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :abeyances
  resources :insurers
  resources :underwriters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'underwriters#new'

end

app/models/abeyance.rb
class Abeyance < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/insurer.rb
class Insurer < ApplicationRecord
end

app/models/underwriter.rb
class Underwriter < ApplicationRecord
  belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/abeyances_controller.rb
class AbeyancesController < ApplicationController
  before_action :set_abeyance, only: [:show, :edit, :update, :destroy]

  # GET /abeyances
  # GET /abeyances.json
  def index
    @abeyances = Abeyance.all
  end

  # GET /abeyances/1
  # GET /abeyances/1.json
  def show
  end

  # GET /abeyances/new
  def new
    @abeyance = Abeyance.new
  end

  # GET /abeyances/1/edit
  def edit
  end

  # POST /abeyances
  # POST /abeyances.json
  def create
    @abeyance = Abeyance.new(abeyance_params)

    respond_to do |format|
      if @abeyance.save
        format.html { redirect_to @abeyance, notice: 'Abeyance was successfully created.' }
        format.json { render :show, status: :created, location: @abeyance }
      else
        format.html { render :new }
        format.json { render json: @abeyance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abeyances/1
  # PATCH/PUT /abeyances/1.json
  def update
    respond_to do |format|
      if @abeyance.update(abeyance_params)
        format.html { redirect_to @abeyance, notice: 'Abeyance was successfully updated.' }
        format.json { render :show, status: :ok, location: @abeyance }
      else
        format.html { render :edit }
        format.json { render json: @abeyance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abeyances/1
  # DELETE /abeyances/1.json
  def destroy
    @abeyance.destroy
    respond_to do |format|
      format.html { redirect_to abeyances_url, notice: 'Abeyance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_abeyance
      @abeyance = Abeyance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def abeyance_params
      params.require(:abeyance).permit(:start_time, :end_time, :title, :reminder)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/insurers_controller.rb
class InsurersController < ApplicationController
  before_action :set_insurer, only: [:show, :edit, :update, :destroy]

  # GET /insurers
  # GET /insurers.json
  def index
    @insurers = Insurer.all
  end

  # GET /insurers/1
  # GET /insurers/1.json
  def show
  end

  # GET /insurers/new
  def new
    @insurer = Insurer.new
  end

  # GET /insurers/1/edit
  def edit
  end

  # POST /insurers
  # POST /insurers.json
  def create
    @insurer = Insurer.new(insurer_params)

    respond_to do |format|
      if @insurer.save
        format.html { redirect_to @insurer, notice: 'Insurer was successfully created.' }
        format.json { render :show, status: :created, location: @insurer }
      else
        format.html { render :new }
        format.json { render json: @insurer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insurers/1
  # PATCH/PUT /insurers/1.json
  def update
    respond_to do |format|
      if @insurer.update(insurer_params)
        format.html { redirect_to @insurer, notice: 'Insurer was successfully updated.' }
        format.json { render :show, status: :ok, location: @insurer }
      else
        format.html { render :edit }
        format.json { render json: @insurer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insurers/1
  # DELETE /insurers/1.json
  def destroy
    @insurer.destroy
    respond_to do |format|
      format.html { redirect_to insurers_url, notice: 'Insurer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insurer
      @insurer = Insurer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insurer_params
      params.require(:insurer).permit(:name)
    end
end

app/controllers/underwriters_controller.rb
class UnderwritersController < ApplicationController
  before_action :set_underwriter, only: [:show, :edit, :update, :destroy]

  # GET /underwriters
  # GET /underwriters.json
  def index
    @underwriters = Underwriter.all
  end

  # GET /underwriters/1
  # GET /underwriters/1.json
  def show
  end

  # GET /underwriters/new
  def new
    @underwriter = Underwriter.new
  end

  # GET /underwriters/1/edit
  def edit
  end

  # POST /underwriters
  # POST /underwriters.json
  def create
    @underwriter = Underwriter.new(underwriter_params)

    respond_to do |format|
      if @underwriter.save
        format.html { redirect_to @underwriter, notice: 'Underwriter was successfully created.' }
        format.json { render :show, status: :created, location: @underwriter }
      else
        format.html { render :new }
        format.json { render json: @underwriter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /underwriters/1
  # PATCH/PUT /underwriters/1.json
  def update
    respond_to do |format|
      if @underwriter.update(underwriter_params)
        format.html { redirect_to @underwriter, notice: 'Underwriter was successfully updated.' }
        format.json { render :show, status: :ok, location: @underwriter }
      else
        format.html { render :edit }
        format.json { render json: @underwriter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /underwriters/1
  # DELETE /underwriters/1.json
  def destroy
    @underwriter.destroy
    respond_to do |format|
      format.html { redirect_to underwriters_url, notice: 'Underwriter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_underwriter
      @underwriter = Underwriter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def underwriter_params
      params.require(:underwriter).permit(:name, :email, :phone, :company_id)
    end
end

app/helpers/abeyances_helper.rb
module AbeyancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/insurers_helper.rb
module InsurersHelper
end

app/helpers/underwriters_helper.rb
module UnderwritersHelper
end

app/views/abeyances/_form.html.erb
<%= form_for(@abeyance, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @abeyance.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@abeyance.errors.count, "error") %> prohibited this abeyance from being saved:</h4>

      <ul>
      <% @abeyance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :start_time, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :start_time, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_time, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :end_time, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :reminder, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :reminder, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/abeyances/edit.html.erb
<div class="page-header">
  <%= link_to abeyances_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @abeyance, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing abeyance</h1>
</div>

<%= render 'form' %>

app/views/abeyances/index.html.erb
<div class="page-header">
  <%= link_to new_abeyance_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Abeyance
  <% end %>
  <h1>Listing abeyances</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Start time</th>
            <th>End time</th>
            <th>Title</th>
            <th>Reminder</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @abeyances) do |abeyance| %>
            <td><%= abeyance.start_time %></td>
            <td><%= abeyance.end_time %></td>
            <td><%= abeyance.title %></td>
            <td><%= abeyance.reminder %></td>
            <td><%= link_to 'Show', abeyance %></td>
        <td><%= link_to 'Edit', edit_abeyance_path(abeyance) %></td>
        <td><%= link_to 'Destroy', abeyance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/abeyances/new.html.erb
<div class="page-header">
  <%= link_to abeyances_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New abeyance</h1>
</div>

<%= render 'form' %>

app/views/abeyances/show.html.erb
<div class="page-header">
  <%= link_to abeyances_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_abeyance_path(@abeyance), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show abeyance</h1>
</div>

<dl class="dl-horizontal">
  <dt>Start time:</dt>
  <dd><%= @abeyance.start_time %></dd>

  <dt>End time:</dt>
  <dd><%= @abeyance.end_time %></dd>

  <dt>Title:</dt>
  <dd><%= @abeyance.title %></dd>

  <dt>Reminder:</dt>
  <dd><%= @abeyance.reminder %></dd>

</dl>

app/views/insurers/_form.html.erb
<%= form_for(@insurer, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @insurer.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@insurer.errors.count, "error") %> prohibited this insurer from being saved:</h4>

      <ul>
      <% @insurer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/insurers/edit.html.erb
<div class="page-header">
  <%= link_to insurers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @insurer, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing insurer</h1>
</div>

<%= render 'form' %>

app/views/insurers/index.html.erb
<div class="page-header">
  <%= link_to new_insurer_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Insurer
  <% end %>
  <h1>Listing insurers</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @insurers) do |insurer| %>
            <td><%= insurer.name %></td>
            <td><%= link_to 'Show', insurer %></td>
        <td><%= link_to 'Edit', edit_insurer_path(insurer) %></td>
        <td><%= link_to 'Destroy', insurer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/insurers/new.html.erb
<div class="page-header">
  <%= link_to insurers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New insurer</h1>
</div>

<%= render 'form' %>

app/views/insurers/show.html.erb
<div class="page-header">
  <%= link_to insurers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_insurer_path(@insurer), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show insurer</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @insurer.name %></dd>

</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Project name", "#", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/underwriters/_form.html.erb
<%= form_for(@underwriter, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @underwriter.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@underwriter.errors.count, "error") %> prohibited this underwriter from being saved:</h4>

      <ul>
      <% @underwriter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :phone, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :company, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/underwriters/edit.html.erb
<div class="page-header">
  <%= link_to underwriters_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @underwriter, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing underwriter</h1>
</div>

<%= render 'form' %>

app/views/underwriters/index.html.erb
<div class="page-header">
  <%= link_to new_underwriter_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Underwriter
  <% end %>
  <h1>Listing underwriters</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Company</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @underwriters) do |underwriter| %>
            <td><%= underwriter.name %></td>
            <td><%= underwriter.email %></td>
            <td><%= underwriter.phone %></td>
            <td><%= underwriter.company %></td>
            <td><%= link_to 'Show', underwriter %></td>
        <td><%= link_to 'Edit', edit_underwriter_path(underwriter) %></td>
        <td><%= link_to 'Destroy', underwriter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/underwriters/new.html.erb
<div class="page-header">
  <%= link_to underwriters_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New underwriter</h1>
</div>

<%= render 'form' %>

app/views/underwriters/show.html.erb
<div class="page-header">
  <%= link_to underwriters_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_underwriter_path(@underwriter), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show underwriter</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @underwriter.name %></dd>

  <dt>Email:</dt>
  <dd><%= @underwriter.email %></dd>

  <dt>Phone:</dt>
  <dd><%= @underwriter.phone %></dd>

  <dt>Company:</dt>
  <dd><%= @underwriter.company %></dd>

</dl>